"""Pydantic schemas for the Daily Standup agent."""

from typing import List, Optional

from pydantic import BaseModel, Field

from shared.schemas.agent_envelope import AgentInputBase, AgentOutputBase


class StandupSummary(BaseModel):
    """The structured summary of the daily standup check-in."""

    yesterday_completed: List[str] = Field(
        ...,
        description="List of tasks completed yesterday based on the founder's update."
    )
    today_priorities: List[str] = Field(
        ...,
        description="Top 2-3 priorities for today's focus (max 3)."
    )
    blockers_identified: List[str] = Field(
        ...,
        description="Any blockers identified from the founder's update."
    )
    momentum_delta: int = Field(
        ...,
        description="Estimated change in momentum score (e.g. -5, 0, 10)."
    )
    encouragement: str = Field(
        ...,
        description="Brief motivational note from the AI co-founder."
    )
    blocker_suggestions: Optional[List[str]] = Field(
        default=None,
        description="Suggestions or actions to unblock identified issues."
    )


class DailyStandupInput(AgentInputBase):
    """Input payload for the Daily Standup agent."""

    founder_update: str = Field(
        ...,
        min_length=5,
        max_length=5000,
        description="Free-text update from the founder about their progress and blockers."
    )
    yesterday_tasks: Optional[List[str]] = Field(
        default=None,
        description="Tasks that were planned for yesterday/last work session."
    )
    today_sprint_tasks: Optional[List[str]] = Field(
        default=None,
        description="Sprint tasks available/scheduled for today."
    )


class DailyStandupLLMOutput(BaseModel):
    standup_summary: StandupSummary = Field(..., description="Distilled summary of the standup.")


class DailyStandupOutput(AgentOutputBase):
    """Output payload generated by the Daily Standup agent."""

    standup_summary: StandupSummary = Field(
        ...,
        description="Distilled summary of the standup."
    )
