"""Pydantic schemas for the 90-Day War Room agent."""

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field

from shared.schemas.agent_envelope import AgentInputBase, AgentOutputBase


class WeeklyGoal(BaseModel):
    """Weekly execution goals within a roadmap phase."""

    week_number: int = Field(..., description="The week number (1 to 12).")
    focus: str = Field(..., description="High-level focus area for the week.")
    goals: List[str] = Field(..., description="3-5 specific, actionable goals for the week.")
    estimated_hours: int = Field(..., description="Estimated hours required to complete these goals.")


class Milestone(BaseModel):
    """A milestone to measure progress in a phase."""

    title: str = Field(..., description="Brief title of the milestone (e.g., 'Product Brief Complete').")
    target_week: int = Field(..., description="The target week number this should be achieved.")
    metric: str = Field(..., description="Specific metric or condition to confirm achievement.")
    target_value: Union[int, str] = Field(..., description="Expected value or target state.")


class Phase(BaseModel):
    """One of the three 30-day phases of the 90-day roadmap."""

    phase_number: int = Field(..., description="Phase number (1, 2, or 3).")
    title: str = Field(..., description="Title of the phase.")
    start_day: int = Field(..., description="Start day (e.g., 1, 31, 61).")
    end_day: int = Field(..., description="End day (e.g., 30, 60, 90).")
    theme: str = Field(..., description="Theme of the phase: e.g., 'Validation', 'Building', 'Launching'.")
    weekly_goals: List[WeeklyGoal] = Field(..., description="Weekly breakdown of goals for the phase.")
    milestones: List[Milestone] = Field(..., description="Phase milestones.")
    success_criteria: List[str] = Field(..., description="Key criteria to declare the phase successful.")
    go_no_go_gate: str = Field(
        ...,
        description="Gate criteria to assess whether to proceed to the next phase."
    )
    key_risks: List[str] = Field(..., description="Key risks identified for this phase.")
    agents_to_use: List[str] = Field(..., description="Karnex agent IDs recommended to run in this phase.")


class Roadmap(BaseModel):
    """The complete 90-day roadmap structured output."""

    title: str = Field(default="90-Day Roadmap", description="Descriptive title for the roadmap.")
    total_days: int = Field(default=90, description="Total duration of the roadmap (always 90).")
    start_date: str = Field(..., description="ISO 8601 start date of the roadmap.")
    phases: List[Phase] = Field(..., description="Exactly 3 sequential phases.")


class FounderCapacity(BaseModel):
    """Capacity and skills information of the founder."""

    weekly_hours: int = Field(
        ...,
        ge=1,
        le=80,
        description="Hours per week the founder has available."
    )
    technical_level: str = Field(
        ...,
        description="Founder's tech experience: 'beginner', 'intermediate', or 'advanced'."
    )
    budget_monthly: int = Field(
        ...,
        ge=0,
        description="Founder's monthly budget in USD."
    )


class WarRoomInput(AgentInputBase):
    """Input payload for the 90-Day War Room agent."""

    product_brief: Dict[str, Any] = Field(
        ...,
        description="Structured product brief dictionary from Idea Crystallizer."
    )
    icp_document: Dict[str, Any] = Field(
        ...,
        description="ICP profile dictionary from ICP Definer."
    )
    founder_capacity: FounderCapacity = Field(
        ...,
        description="Founder's capacity and preference settings."
    )
    start_date: Optional[str] = Field(
        None,
        description="ISO date string for start of the roadmap. Defaults to today."
    )


class WarRoomLLMOutput(BaseModel):
    roadmap: Roadmap = Field(..., description="The structured 90-day roadmap.")


class WarRoomOutput(AgentOutputBase):
    """Output payload generated by the 90-Day War Room agent."""

    roadmap: Roadmap = Field(
        ...,
        description="The structured 90-day roadmap."
    )
