"""Pydantic schemas for the Outreach agent."""

from typing import List, Optional

from pydantic import BaseModel, Field

from shared.schemas.agent_envelope import AgentInputBase, AgentOutputBase


class OutreachContact(BaseModel):
    """Information about a contact to be reached."""

    first_name: Optional[str] = Field(None, description="Contact first name.")
    last_name: Optional[str] = Field(None, description="Contact last name.")
    email: Optional[str] = Field(None, description="Contact email address.")
    company: Optional[str] = Field(None, description="Company name.")
    title: Optional[str] = Field(None, description="Contact job title.")
    linkedin_url: Optional[str] = Field(None, description="Contact LinkedIn profile URL.")


class CampaignMessage(BaseModel):
    """A template email message for a sequence step."""

    step: int = Field(..., description="Sequence step (1, 2, 3...).")
    delay_days: int = Field(..., description="Days to delay since the previous message.")
    subject: str = Field(..., description="Subject template (e.g. 'Question about {{company}}').")
    body: str = Field(..., description="Email body template (e.g. 'Hi {{first_name}}, ...').")
    variant: str = Field("A", description="Variant identifier: 'A' or 'B'.")


class SendSchedule(BaseModel):
    """Recommended schedule for sending campaign emails."""

    best_days: List[str] = Field(..., description="Recommended days, e.g. ['Tuesday', 'Wednesday', 'Thursday']")
    time_of_day: str = Field(..., description="Recommended time window, e.g. '09:00 - 11:00'")
    timezone: str = Field(..., description="Target timezone context.")


class CampaignDetails(BaseModel):
    """Comprehensive details of the generated outreach campaign."""

    name: str = Field(..., description="Memorable campaign name.")
    messages: List[CampaignMessage] = Field(..., description="The standard sequence steps (Variant A).")
    send_schedule: SendSchedule = Field(..., description="Schedule recommendation.")
    personalization_notes: str = Field(..., description="Notes on how to customize messages.")
    ab_variants: Optional[List[CampaignMessage]] = Field(
        None, description="A/B test variants (usually Variant B for Step 1)."
    )


class OutreachInput(AgentInputBase):
    """Input payload for the Outreach agent."""

    startup_id: str = Field(..., description="Unique ID of the startup.")
    campaign_goal: str = Field(
        ...,
        description="The goal of the campaign (e.g., 'Get 20 beta signups')."
    )
    target_audience: str = Field(
        ...,
        description="The ideal customer profile / target audience segment."
    )
    contacts: List[OutreachContact] = Field(
        ...,
        description="List of contacts to reach."
    )
    channel: str = Field(
        "email",
        description="Communication channel: 'email' or 'linkedin'."
    )
    tone: Optional[str] = Field(
        "direct",
        description="Tone of the messages: 'formal', 'casual', or 'direct'."
    )
    sequence_length: Optional[int] = Field(
        3,
        ge=1,
        le=5,
        description="Number of steps in the sequence."
    )
    reference_content: Optional[str] = Field(
        None,
        description="Optional additional reference content (product brief, etc.)."
    )


class OutreachLLMOutput(BaseModel):
    campaign: CampaignDetails = Field(..., description="The generated campaign details.")
    requires_approval: bool = Field(True, description="Always True.")


class OutreachOutput(AgentOutputBase):
    """Output payload generated by the Outreach agent."""

    campaign: CampaignDetails = Field(..., description="The generated campaign details.")
    requires_approval: bool = Field(True, description="Always True.")
