'use client'

import React, { useState, useEffect, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { createSupabaseBrowserClient } from '@/lib/supabase/client'
import { Skeleton } from '@/components/Skeleton'
import { ErrorBoundary } from '@/components/ErrorBoundary'

interface ProductHypothesis {
  title: string
  problem_statement: string
  proposed_solution: string
  target_audience: string
  market_size_estimate: string
  pain_intensity_score: number
  market_size_score: number
  buildability_score: number
  overall_score: number
  key_risks: string[]
  next_steps: string[]
}

interface IdeaRecord {
  id: string
  title: string
  pain_description: string
  problem_statement: string
  proposed_solution: string
  pain_intensity_score: number
  market_size_score: number
  buildability_score: number
  overall_score: number
  status: 'hypothesis' | 'exploring' | 'validated' | 'rejected' | 'selected'
  product_brief: {
    title?: string
    problem_statement?: string
    proposed_solution?: string
    target_audience?: string
    market_size_estimate?: string
  } | null
  icp_document: {
    target_audience?: string
    key_risks?: string[]
    next_steps?: string[]
  } | null
  created_at: string
}

const AGENT_SERVICE_URL = process.env.NEXT_PUBLIC_AGENT_SERVICE_URL || 'http://localhost:8000'

export default function IdeasPage() {
  return (
    <ErrorBoundary>
      <IdeasContent />
    </ErrorBoundary>
  )
}

function IdeasContent() {
  const router = useRouter()
  const supabase = createSupabaseBrowserClient()

  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [startupId, setStartupId] = useState('')
  const [painInput, setPainInput] = useState('')
  const [ideas, setIdeas] = useState<IdeaRecord[]>([])
  
  // Hypotheses generated by the pain-transformer agent
  const [generatedHypotheses, setGeneratedHypotheses] = useState<ProductHypothesis[] | null>(null)
  const [recommendedIndex, setRecommendedIndex] = useState<number | null>(null)

  // Initialize startup context and fetch existing ideas
  const initPage = useCallback(async () => {
    try {
      setLoading(true)
      const { data: { session } } = await supabase.auth.getSession()
      if (!session) return

      // 1. Ensure founder profile exists
      const { data: founder } = await supabase
        .from('founders')
        .select('id')
        .eq('id', session.user.id)
        .maybeSingle()

      if (!founder) {
        const fullName = session.user.user_metadata?.full_name || session.user.email?.split('@')[0] || 'Founder'
        await supabase
          .from('founders')
          .insert({
            id: session.user.id,
            full_name: fullName,
            display_name: fullName,
            technical_level: 'intermediate',
            weekly_hours_available: 20,
            momentum_score: 50,
            streak_days: 0
          })
      }

      // 2. Resolve active startup profile
      let activeStartupId = ''
      const { data: startup } = await supabase
        .from('startups')
        .select('id')
        .eq('founder_id', session.user.id)
        .eq('is_active', true)
        .limit(1)
        .maybeSingle()

      if (startup) {
        activeStartupId = startup.id
        setStartupId(startup.id)
      } else {
        // Create default startup profile if none exists
        const { data: newStartup } = await supabase
          .from('startups')
          .insert({
            founder_id: session.user.id,
            name: `${session.user.user_metadata?.full_name || session.user.email?.split('@')[0] || 'Founder'}'s Startup`,
            description: 'Created by Karnex co-founder',
            is_active: true
          })
          .select()
          .single()
        if (newStartup) {
          activeStartupId = newStartup.id
          setStartupId(newStartup.id)

          // Update founder current_startup_id
          await supabase
            .from('founders')
            .update({ current_startup_id: newStartup.id })
            .eq('id', session.user.id)
        }
      }

      if (!activeStartupId) return

      // 2. Fetch validated ideas for this startup
      const { data: ideasList } = await supabase
        .from('ideas')
        .select('*')
        .eq('startup_id', activeStartupId)
        .order('created_at', { ascending: false })

      if (ideasList) {
        setIdeas(ideasList as IdeaRecord[])
      }
    } catch (err) {
      console.error('Error initializing ideas page:', err)
    } finally {
      setLoading(false)
    }
  }, [supabase])

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    initPage()
  }, [initPage])

  const handleExtractWedge = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!painInput.trim()) return
    if (!startupId) {
      alert('Startup context is not initialized. Please verify settings.')
      return
    }

    try {
      setGenerating(true)
      setGeneratedHypotheses(null)
      setRecommendedIndex(null)

      const { data: { session } } = await supabase.auth.getSession()
      if (!session) return

      const token = session.access_token

      const response = await fetch(`${AGENT_SERVICE_URL}/v1/agents/pain-transformer`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          pain_description: painInput
        })
      })

      if (!response.ok) {
        throw new Error('Failed to run pain transformer agent')
      }

      const result = await response.json()
      if (result && result.hypotheses) {
        setGeneratedHypotheses(result.hypotheses)
        setRecommendedIndex(result.recommended_hypothesis ?? 0)
      }
    } catch (err) {
      console.error(err)
      alert('Failed to analyze pain inputs. Make sure agent service is configured and running.')
    } finally {
      setGenerating(false)
    }
  }

  const handleSaveHypothesis = async (hyp: ProductHypothesis) => {
    try {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session) return

      const { error } = await supabase
        .from('ideas')
        .insert({
          startup_id: startupId,
          founder_id: session.user.id,
          title: hyp.title,
          pain_description: painInput,
          problem_statement: hyp.problem_statement,
          proposed_solution: hyp.proposed_solution,
          pain_intensity_score: hyp.pain_intensity_score,
          market_size_score: hyp.market_size_score,
          buildability_score: hyp.buildability_score,
          overall_score: hyp.overall_score,
          status: 'validated',
          product_brief: {
            title: hyp.title,
            problem_statement: hyp.problem_statement,
            proposed_solution: hyp.proposed_solution,
            target_audience: hyp.target_audience,
            market_size_estimate: hyp.market_size_estimate
          },
          icp_document: {
            target_audience: hyp.target_audience,
            key_risks: hyp.key_risks,
            next_steps: hyp.next_steps
          }
        })

      if (error) throw error

      // Clear generation state and reload ideas
      setGeneratedHypotheses(null)
      setRecommendedIndex(null)
      setPainInput('')
      initPage()
    } catch (err) {
      console.error(err)
      alert('Failed to save validated idea to database.')
    }
  }

  const handleSelectIdea = async (ideaId: string) => {
    try {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session) return

      // Reset other ideas status to 'validated'
      await supabase
        .from('ideas')
        .update({ status: 'validated' })
        .eq('founder_id', session.user.id)
        .eq('status', 'selected')

      // Set chosen idea status to 'selected'
      const { error } = await supabase
        .from('ideas')
        .update({ status: 'selected' })
        .eq('id', ideaId)

      if (error) throw error

      // Redirect to War Room to build roadmap for this selected idea
      router.push('/warroom')
    } catch (err) {
      console.error(err)
      alert('Failed to select active idea.')
    }
  }

  const handleDeleteIdea = async (ideaId: string) => {
    if (!confirm('Are you sure you want to delete this idea?')) return
    try {
      const { error } = await supabase
        .from('ideas')
        .delete()
        .eq('id', ideaId)

      if (error) throw error
      initPage()
    } catch (err) {
      console.error(err)
      alert('Failed to delete idea.')
    }
  }

  return (
    <div className="mx-auto max-w-5xl space-y-8 pb-12">
      {/* Header */}
      <div className="border-b border-[#1a1a1a] pb-6">
        <h1 className="font-display text-3xl font-bold text-white">
          Dream Engine
        </h1>
        <p className="mt-1.5 text-sm text-zinc-500">
          Transform raw frustrations, daily annoyances, and target customer complaints into validated product opportunities.
        </p>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left Form Panel */}
        <div className="lg:col-span-2 space-y-6">
          <div className="rounded-xl border border-[#1a1a1a] bg-[#07070a] p-6 space-y-4">
            <h2 className="text-sm font-semibold text-zinc-200 tracking-tight">
              Pain-to-Product Transformer
            </h2>
            <p className="text-xs text-zinc-500 leading-relaxed">
              Paste customer feedback, app store complaints, or your own daily workflow bottlenecks. Our agents will dissect it for latent software opportunities.
            </p>
            
            <form onSubmit={handleExtractWedge} className="space-y-4">
              <div className="space-y-2">
                <label className="text-[10px] font-semibold text-zinc-400 uppercase tracking-wider font-mono">
                  Raw Input Data
                </label>
                <textarea
                  value={painInput}
                  onChange={(e) => setPainInput(e.target.value)}
                  placeholder="E.g., I spend 2 hours every week mapping client invoices to stripe payments. It should be automated. Customers complain that the invoice layout is too complicated..."
                  rows={6}
                  className="w-full rounded-lg border border-[#1a1a1a] bg-[#030303] px-3.5 py-2.5 text-sm text-white placeholder-zinc-600 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 font-sans transition-all resize-none"
                  required
                />
              </div>

              <button
                type="submit"
                disabled={generating || !painInput.trim()}
                className="w-full flex items-center justify-center gap-2 rounded-lg bg-indigo-500 hover:bg-indigo-600 px-4 py-2.5 text-xs font-semibold text-white transition-all cursor-pointer shadow-md shadow-indigo-500/10 disabled:opacity-40 disabled:cursor-not-allowed"
              >
                {generating ? (
                  <>
                    <svg className="h-4 w-4 animate-spin text-white" viewBox="0 0 24 24" fill="none">
                      <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" className="opacity-25" />
                      <path d="M4 12a8 8 0 018-8" stroke="currentColor" strokeWidth="3" strokeLinecap="round" className="opacity-75" />
                    </svg>
                    Analyzing Frustrations...
                  </>
                ) : (
                  <>
                    <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 21l8.982-11.795M20.618 3.518a.75.75 0 01.03 1.06l-1.42 1.42a9 9 0 00-12.68 0l-1.42-1.42a.75.75 0 111.06-1.06l1.42 1.42a7.5 7.5 0 0110.56 0l1.42-1.42a.75.75 0 011.06 0z" />
                    </svg>
                    Extract Product Wedge
                  </>
                )}
              </button>
            </form>
          </div>

          {/* AI Generated Candidates Section */}
          {generatedHypotheses && (
            <div className="space-y-4 border border-violet-500/20 bg-violet-500/[0.02] p-5 rounded-xl">
              <h2 className="text-xs font-bold text-violet-400 tracking-wider uppercase font-mono">
                AI Suggested Product Hypotheses
              </h2>
              <div className="grid grid-cols-1 gap-4">
                {generatedHypotheses.map((hyp, index) => {
                  const isRecommended = index === recommendedIndex
                  return (
                    <div 
                      key={index} 
                      className={`rounded-xl border p-5 bg-black/40 space-y-4 transition-all ${
                        isRecommended ? 'border-violet-500/40 ring-1 ring-violet-500/20' : 'border-[#1a1a1a]'
                      }`}
                    >
                      <div className="flex items-start justify-between gap-4">
                        <div>
                          <div className="flex items-center gap-2 flex-wrap">
                            <h3 className="text-sm font-bold text-zinc-100">{hyp.title}</h3>
                            {isRecommended && (
                              <span className="rounded-full bg-violet-500/10 px-2 py-0.5 text-[9px] font-bold text-violet-400 ring-1 ring-inset ring-violet-500/20 font-mono">
                                RECOMMENDED WEDGE
                              </span>
                            )}
                          </div>
                          <p className="mt-2 text-xs text-zinc-300 leading-relaxed">
                            <span className="text-zinc-500 font-semibold font-mono uppercase text-[9px] mr-1">Problem:</span>
                            {hyp.problem_statement}
                          </p>
                          <p className="mt-2 text-xs text-zinc-300 leading-relaxed">
                            <span className="text-zinc-500 font-semibold font-mono uppercase text-[9px] mr-1">Proposed Solution:</span>
                            {hyp.proposed_solution}
                          </p>
                        </div>
                        <div className="text-right shrink-0">
                          <span className="rounded bg-indigo-500/15 px-2 py-1 text-[10px] font-bold text-indigo-300 border border-indigo-500/20 font-mono">
                            Score: {hyp.overall_score}/100
                          </span>
                        </div>
                      </div>

                      <div className="grid grid-cols-3 gap-2 py-3 border-y border-[#1a1a1a] text-[10px] font-mono">
                        <div>
                          <span className="text-zinc-600 block">PAIN INTENSITY</span>
                          <span className="text-zinc-300 font-bold">{hyp.pain_intensity_score}/100</span>
                        </div>
                        <div>
                          <span className="text-zinc-600 block">MARKET POTENTIAL</span>
                          <span className="text-zinc-300 font-bold">{hyp.market_size_score}/100</span>
                        </div>
                        <div>
                          <span className="text-zinc-600 block">BUILD FEASIBILITY</span>
                          <span className="text-zinc-300 font-bold">{hyp.buildability_score}/100</span>
                        </div>
                      </div>

                      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pt-1">
                        <div className="text-[11px] text-zinc-400">
                          <span className="text-zinc-500 font-semibold font-mono uppercase text-[9px] mr-1">Monetization Estimate:</span>
                          {hyp.market_size_estimate}
                        </div>
                        <button
                          type="button"
                          onClick={() => handleSaveHypothesis(hyp)}
                          className="rounded bg-indigo-600 hover:bg-indigo-500 px-3.5 py-1.5 text-[11px] font-semibold text-white transition-all shadow-md shadow-indigo-600/10 cursor-pointer self-stretch sm:self-auto text-center"
                        >
                          Validate & Save Idea
                        </button>
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          )}

          {/* Validated Ideas Feed */}
          <div className="space-y-4">
            <h2 className="text-xs font-semibold text-zinc-500 tracking-wider uppercase font-mono">
              Validated Product Hypotheses
            </h2>
            
            {loading ? (
              <div className="space-y-4">
                <Skeleton className="h-28 rounded-xl" />
                <Skeleton className="h-28 rounded-xl" />
              </div>
            ) : ideas.length > 0 ? (
              <div className="space-y-4">
                {ideas.map((idea) => {
                  const isSelected = idea.status === 'selected'
                  return (
                    <div 
                      key={idea.id} 
                      className={`rounded-xl border p-5 bg-[#07070a] space-y-4 transition-all hover:border-zinc-700 ${
                        isSelected ? 'border-emerald-500/30 bg-[#070908]' : 'border-[#1a1a1a]'
                      }`}
                    >
                      <div className="flex items-start justify-between gap-4">
                        <div>
                          <div className="flex items-center gap-2 flex-wrap">
                            <h3 className="text-sm font-semibold text-zinc-200">{idea.title}</h3>
                            {isSelected && (
                              <span className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-[9px] font-bold text-emerald-400 ring-1 ring-inset ring-emerald-500/20 font-mono">
                                ACTIVE SELECTED
                              </span>
                            )}
                          </div>
                          <p className="mt-1 text-xs text-zinc-400 leading-relaxed">
                            <span className="text-zinc-500 font-medium">Pain Bottleneck:</span> {idea.pain_description}
                          </p>
                          <p className="mt-2 text-xs text-zinc-300 leading-relaxed">
                            <span className="text-zinc-500 font-medium">Proposed Solution:</span> {idea.proposed_solution}
                          </p>
                        </div>
                        
                        <div className="flex flex-col items-end gap-2 shrink-0">
                          <span className="rounded bg-indigo-500/5 px-2 py-0.5 text-[10px] font-semibold text-indigo-400 ring-1 ring-inset ring-indigo-500/20 font-mono">
                            Score: {idea.overall_score}/100
                          </span>
                          <button
                            onClick={() => handleDeleteIdea(idea.id)}
                            className="text-zinc-600 hover:text-red-400 text-[10px] font-mono hover:underline transition-colors"
                          >
                            delete
                          </button>
                        </div>
                      </div>

                      <div className="border-t border-[#1a1a1a]/60 pt-3 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                        <div className="text-[11px] text-zinc-500 leading-normal">
                          <span className="text-zinc-400 font-semibold font-mono uppercase text-[9px] tracking-wide mr-1">Moat Wedge:</span>
                          {idea.product_brief?.proposed_solution || 'N/A'}
                        </div>
                        
                        {!isSelected ? (
                          <button
                            type="button"
                            onClick={() => handleSelectIdea(idea.id)}
                            className="rounded bg-zinc-800 hover:bg-zinc-700 text-zinc-200 px-3 py-1.5 text-[10px] font-semibold transition-all border border-zinc-700 hover:border-zinc-600 shrink-0 self-stretch sm:self-auto text-center"
                          >
                            Select for War Room &rarr;
                          </button>
                        ) : (
                          <button
                            type="button"
                            onClick={() => router.push('/warroom')}
                            className="rounded bg-emerald-950/40 hover:bg-emerald-900/40 text-emerald-400 px-3 py-1.5 text-[10px] font-semibold transition-all border border-emerald-500/20 shrink-0 self-stretch sm:self-auto text-center"
                          >
                            Open Active War Room &rarr;
                          </button>
                        )}
                      </div>
                    </div>
                  )
                })}
              </div>
            ) : (
              <div className="rounded-xl border border-[#1a1a1a] bg-[#07070a] p-12 text-center text-zinc-600">
                <p className="text-sm">No validated product hypotheses saved yet. Add raw bottlenecks above.</p>
              </div>
            )}
          </div>
        </div>

        {/* Right Stats & Sidebar */}
        <div className="space-y-6">
          
          {/* Intelligence Score */}
          <div className="rounded-xl border border-[#1a1a1a] bg-[#07070a] p-6 space-y-4">
            <span className="text-xs font-semibold text-zinc-500 tracking-wider uppercase font-mono">
              Market Intelligence
            </span>
            <div className="flex items-baseline gap-1">
              <span className="text-4xl font-bold text-white tracking-tight">{ideas.length}</span>
              <span className="text-xs text-zinc-500 font-semibold">Ideas Analyzed</span>
            </div>
            <div className="border-t border-[#1a1a1a] pt-4 space-y-3 text-xs">
              <div className="flex items-center justify-between">
                <span className="text-zinc-500">Validation Speed</span>
                <span className="font-semibold text-zinc-300">Fast (24h)</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-zinc-500">Competitive density scan</span>
                <span className="font-semibold text-zinc-300">Active</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-zinc-500">Target ICP definition</span>
                <span className="font-semibold text-emerald-400">Complete</span>
              </div>
            </div>
          </div>

          {/* Socratic Questions */}
          <div className="rounded-xl border border-[#1a1a1a] bg-[#07070a] p-6 space-y-3">
            <h3 className="text-xs font-semibold text-zinc-400 tracking-wider uppercase font-mono">
              Idea Crystallizer Checklist
            </h3>
            <p className="text-[11px] text-zinc-500 leading-relaxed">
              Every crystallized idea goes through a Socratic check across 4 critical dimensions before it hits the War Room.
            </p>
            <ul className="space-y-2.5 text-[11px] pt-2">
              <li className="flex items-center gap-2 text-zinc-400">
                <span className="flex h-4 w-4 items-center justify-center rounded-full bg-emerald-500/10 text-emerald-400 font-mono text-[9px] font-bold">1</span>
                Who suffers from the bottleneck?
              </li>
              <li className="flex items-center gap-2 text-zinc-400">
                <span className="flex h-4 w-4 items-center justify-center rounded-full bg-emerald-500/10 text-emerald-400 font-mono text-[9px] font-bold">2</span>
                What is the current manual workaround?
              </li>
              <li className="flex items-center gap-2 text-zinc-400">
                <span className="flex h-4 w-4 items-center justify-center rounded-full bg-indigo-500/10 text-indigo-400 font-mono text-[9px] font-bold">3</span>
                What is the unique technological unlock?
              </li>
              <li className="flex items-center gap-2 text-zinc-400">
                <span className="flex h-4 w-4 items-center justify-center rounded-full bg-zinc-800 text-zinc-600 font-mono text-[9px] font-bold">4</span>
                What is the monetization engine?
              </li>
            </ul>
          </div>
        </div>

      </div>
    </div>
  )
}
