"""Pydantic schemas for the Pain-to-Product Transformer agent."""

from typing import List, Optional
from pydantic import BaseModel, Field


class ProductHypothesis(BaseModel):
    """A product hypothesis generated from the founder's pain description."""

    title: str = Field(
        ...,
        description="Short, memorable product name idea."
    )
    problem_statement: str = Field(
        ...,
        description="Structured problem framing (2-3 sentences)."
    )
    proposed_solution: str = Field(
        ...,
        description="How this product solves the problem (2-3 sentences)."
    )
    target_audience: str = Field(
        ...,
        description="Specific target audience description."
    )
    market_size_estimate: str = Field(
        ...,
        description="Estimate of the market size: 'Small niche', 'Growing market', or 'Large market'."
    )
    pain_intensity_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Pain intensity score from 0 (minor annoyance) to 100 (crucial immediate need)."
    )
    market_size_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Market size score from 0 (very small) to 100 (huge potential)."
    )
    buildability_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Buildability score from 0 (extremely complex/months to build) to 100 (can build in weeks)."
    )
    overall_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Weighted average overall score: (Pain * 0.4) + (Market * 0.3) + (Buildability * 0.3)."
    )
    key_risks: List[str] = Field(
        ...,
        min_items=3,
        max_items=3,
        description="Top 3 key risks associated with this hypothesis."
    )
    next_steps: List[str] = Field(
        ...,
        min_items=3,
        max_items=3,
        description="Top 3 next validation steps."
    )


class PainAnalysis(BaseModel):
    """Distilled analysis of the submitted pain description."""

    core_pain: str = Field(
        ...,
        description="The distilled, specific pain statement (1-2 sentences)."
    )
    pain_intensity: int = Field(
        ...,
        ge=0,
        le=100,
        description="Aggregated pain intensity score."
    )
    affected_audience: str = Field(
        ...,
        description="Description of who else feels this pain (roles, demographics)."
    )
    frequency: str = Field(
        ...,
        description="How often this pain is felt: 'daily', 'weekly', 'monthly', or 'situational'."
    )
    existing_alternatives: List[str] = Field(
        ...,
        description="How people currently cope with this pain."
    )


class PainTransformerInput(BaseModel):
    """Input payload for the Pain-to-Product Transformer agent."""

    pain_description: str = Field(
        ...,
        min_length=10,
        max_length=5000,
        description="Raw description of the founder's pain or frustration."
    )
    industry_context: Optional[str] = Field(
        None,
        description="Optional high-level industry description."
    )
    existing_solutions: Optional[List[str]] = Field(
        None,
        description="Optional solutions the founder has already tried."
    )
    founder_id: str = Field(
        ...,
        description="Unique ID of the founder running the agent."
    )


class PainTransformerOutput(BaseModel):
    """Output payload generated by the Pain-to-Product Transformer agent."""

    pain_analysis: PainAnalysis = Field(
        ...,
        description="Core analysis of the founder's frustration."
    )
    hypotheses: List[ProductHypothesis] = Field(
        ...,
        min_items=3,
        max_items=3,
        description="Exactly 3 distinct product hypotheses."
    )
    recommended_hypothesis: int = Field(
        ...,
        ge=0,
        le=2,
        description="Index of the best recommended hypothesis (0, 1, or 2)."
    )
